Update encrypt/decrypt API to add and remove padding (similar to C++ API for nacl)
registreerocks/rtc-data pull request #53
Opened 2021-05-11 10:42 UTC by longtomjr

Closes: #51

2021-05-11 12:39 UTC, PiDelport commented
(Rebased for Makefile fix: #54)

2021-05-11 16:12 UTC, PiDelport requested changes

2021-05-11 16:12 UTC, PiDelport commented on rtc_tenclave/src/crypto.rs
> +                ciphertext.truncate(CRYPTO_BOX_BOXZEROBYTES);
This should probably be the padded length minus the padding?

```suggestion
                ciphertext.truncate(ciphertext.len() - CRYPTO_BOX_BOXZEROBYTES);
```

2021-05-11 16:12 UTC, PiDelport commented on rtc_tenclave/src/crypto.rs
>              &mut message,
The return result below still retains the padding for `message`… this should probably be stripped, for this PR?

2021-05-11 16:31 UTC, longtomjr commented on rtc_tenclave/src/crypto.rs
> +                ciphertext.truncate(CRYPTO_BOX_BOXZEROBYTES);
Thanks for catching this!

2021-05-11 16:31 UTC, longtomjr commented on rtc_tenclave/src/crypto.rs
>              &mut message,
Thanks for catching this.

2021-05-12 13:22 UTC, PiDelport commented on rtc_tenclave/src/crypto.rs
>              &mut message,
@longtomjr: I added some code to strip the prefix. 🚀

2021-05-12 13:23 UTC, PiDelport approved these changes
@longtomjr: Cool, feedback addressed! 🎉

Can you review the prefix stripping code I added?

2021-05-12 13:28 UTC, Nghondzweni approved these changes
Looking good.

2021-05-13 07:49 UTC, longtomjr commented
@PiDelport @Nghondzweni. Please just have a peek at the last 2 commits where I added the tests, and then we can get this merged

2021-05-13 14:52 UTC, PiDelport commented
(Refreshed)

2021-05-13 15:46 UTC, PiDelport approved these changes
Looks good! 🎉

I added some small readability tweaks to make the failure messages clearer about what's failing: I'll go ahead and merge.

2021-05-13 15:46 UTC, merged